<!DOCTYPE html>
<html lang="en">

	<head>
		<meta charset="utf-8">
		<title> Team Berlin | Assignment 02: Smash Website </title>
		<link rel="stylesheet" href="css/styles.css">
	</head>

	<body class="container">

		<header>
			<a href="index.php">
				<h1 class="homeh1" style = "font-size: 1.2em; left: -65px; font-size: 30px;" > Welcome to our page </h1>
				<img src="images/berlin.jpg" alt="Seattle">
			</a>
		</header>

		<aside>
			<p> Hello World. <br> This is the Second Assignment. <br> We are Team Berlin.</p>
		</aside>